# Generated by Django 2.1.10 on 2020-12-25 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('look', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dapartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='学院')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='姓名')),
                ('age', models.IntegerField(max_length=20, verbose_name='年龄')),
                ('gender', models.BooleanField(default=True)),
                ('dapartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='look.Dapartment')),
            ],
        ),
    ]
